### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by ciseng** [atricore/node-uma#1]
Just a quick question about the quick start - does it expect all the routes to be set-up for login etc?
Or we have to set all that before we can do the quick start?

**Comment by gbrigandi** [comment]
Hi, 
Indeed, you need to the authentication and consent capabilities (realized by the authentication server) by building on your preferred stack. For instance, you could build those on top of an AngularJS app.
Here's a example which might inspire you in order to get the barebones of the aforementioned services up and running quickly : https://github.com/agmoyano/OpenIDConnect/blob/master/examples/openid-connect-example.js . 

Alternatively, if you want to explore a more production-level (Java) implementation you might want to look at Mitre's OpenID Connect implementation  : https://github.com/mitreid-connect/

Gianluca.

**Comment by ciseng** [comment]
Hello,
Thanks for the links! Will start exploring.  
--Cigdem
